# Generated by Django 5.2.16 on 2026-08-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "organization",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("guideline", "Clinical guideline body"),
                            ("government", "Government / health authority"),
                            ("journal", "Peer-reviewed journal"),
                            ("textbook", "Textbook / reference work"),
                            ("internal", "Internal Roshada material"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("url", models.URLField(blank=True, default="", max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(blank=True, default="en", max_length=20)),
                ("specialty", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["verification_status"],
                        name="knowledge_k_verific_a2138c_idx",
                    ),
                    models.Index(
                        fields=["specialty"], name="knowledge_k_special_6e1864_idx"
                    ),
                    models.Index(
                        fields=["language"], name="knowledge_k_languag_fd601a_idx"
                    ),
                ],
            },
        ),
    ]
