# Generated by Django 5.2.16 on 2026-08-15 22:31

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "generic_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("strength", models.CharField(blank=True, default="", max_length=60)),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("syrup", "Syrup"),
                            ("suspension", "Suspension"),
                            ("injection", "Injection"),
                            ("cream", "Cream"),
                            ("ointment", "Ointment"),
                            ("drops", "Drops"),
                            ("inhaler", "Inhaler"),
                            ("suppository", "Suppository"),
                            ("other", "Other"),
                        ],
                        default="tablet",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("code", models.CharField(blank=True, default="", max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "strength"],
                "indexes": [
                    models.Index(fields=["name"], name="pharmacy_me_name_46a660_idx"),
                    models.Index(
                        fields=["generic_name"], name="pharmacy_me_generic_3b0dc0_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="pharmacy_me_is_acti_1b417e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        django.db.models.functions.text.Lower("strength"),
                        django.db.models.functions.text.Lower("form"),
                        name="unique_medication_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.CharField(blank=True, default="", max_length=200)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="written_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready for pickup"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("stock_reserved", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "pharmacy_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_medication_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="pharmacy.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosage", models.CharField(blank=True, default="", max_length=120)),
                ("frequency", models.CharField(blank=True, default="", max_length=120)),
                ("duration", models.CharField(blank=True, default="", max_length=120)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "instructions",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescribed_as",
                        to="pharmacy.medication",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MedicationRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_as",
                        to="pharmacy.medication",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.medicationrequest",
                    ),
                ),
                (
                    "prescription_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_as",
                        to="pharmacy.prescriptionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("reserved", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("low_stock_threshold", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocked_by",
                        to="pharmacy.medication",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "pharmacy inventory",
                "ordering": ["medication__name"],
                "indexes": [
                    models.Index(
                        fields=["medication", "is_active"],
                        name="pharmacy_ph_medicat_6f1c91_idx",
                    ),
                    models.Index(
                        fields=["pharmacy", "is_active"],
                        name="pharmacy_ph_pharmac_848e7f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pharmacy", "medication"),
                        name="unique_medication_per_pharmacy",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reserved__lte", models.F("quantity"))),
                        name="inventory_reserved_within_stock",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "-created_at"], name="pharmacy_pr_patient_e5426f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["doctor", "-created_at"], name="pharmacy_pr_doctor__896a35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["status"], name="pharmacy_pr_status_3f9cad_idx"),
        ),
        migrations.AddIndex(
            model_name="medicationrequest",
            index=models.Index(
                fields=["patient", "-created_at"], name="pharmacy_me_patient_60b4c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationrequest",
            index=models.Index(
                fields=["pharmacy", "-created_at"],
                name="pharmacy_me_pharmac_a8534b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicationrequest",
            index=models.Index(fields=["status"], name="pharmacy_me_status_d11725_idx"),
        ),
        migrations.AddIndex(
            model_name="medicationrequest",
            index=models.Index(
                fields=["prescription"], name="pharmacy_me_prescri_1b5d03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionitem",
            index=models.Index(
                fields=["medication"], name="pharmacy_pr_medicat_dba79c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="prescriptionitem",
            constraint=models.UniqueConstraint(
                fields=("prescription", "medication"),
                name="unique_medication_per_prescription",
            ),
        ),
        migrations.AddConstraint(
            model_name="prescriptionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="prescription_item_quantity_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="medicationrequestitem",
            index=models.Index(
                fields=["medication"], name="pharmacy_me_medicat_886864_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationrequestitem",
            constraint=models.UniqueConstraint(
                fields=("request", "medication"), name="unique_medication_per_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="request_item_quantity_positive",
            ),
        ),
    ]
