"""
Django settings for the ROSHDA project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file if python-dotenv is available.
# The import is guarded so the project still starts if the package is not installed.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG is OFF by default and must be explicitly enabled for local development.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
# The key is read from the environment. A throwaway dev key is only used while
# DEBUG is on; running with DEBUG off REQUIRES a real DJANGO_SECRET_KEY.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key-change-me-in-production'
    else:
        raise RuntimeError(
            'DJANGO_SECRET_KEY environment variable must be set when DEBUG is False.'
        )

# Comma-separated list of allowed hosts, e.g. "example.com,api.example.com".
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get(
        'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1'
    ).split(',') if h.strip()
]

# Origins trusted for unsafe (POST/PUT) cross-site requests behind HTTPS.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Required by the appointment engine's ExclusionConstraint (range types and
    # the btree_gist operator class that make overlap detection an index).
    'django.contrib.postgres',
    'rest_framework',
    # Identity: roles, account status and the facility profiles. Listed before
    # 'appointments' because the scheduling domain depends on it, not the other
    # way round — the future Lab/Radiology/Pharmacy apps will depend on it too.
    'accounts',
    'appointments',
    # The aggregation layer. Listed before the clinical modules because they
    # register their timeline sources with it — the dependency runs domain ->
    # records, the same direction as domain -> appointments, so 'records' never
    # imports a clinical module.
    'records',
    # The communication layer: one notification table for the whole platform,
    # plus patient<->doctor messaging. Sits here for the same reason 'records'
    # does — the clinical modules call into it, never the other way round.
    'comms',
    # The Medical Knowledge Base: source governance over the existing RAG
    # corpus. Depends on 'appointments' for the corpus models and the
    # ingestion engine; nothing depends on it.
    'knowledge',
    # Clinical domain modules. They depend on 'appointments' for scheduling,
    # on 'accounts' for identity and on 'records' for publishing history;
    # nothing depends on them, so a module can be added or removed without
    # touching the engine.
    'radiology',
    'pharmacy',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Auth tokens expire after this many hours; the next successful login issues a
# fresh one. 0 disables expiry (stock DRF behaviour: tokens valid forever).
AUTH_TOKEN_TTL_HOURS = int(os.environ.get('AUTH_TOKEN_TTL_HOURS', '24'))

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'appointments.authentication.ExpiringTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Standardises every error response and logs it.
    'EXCEPTION_HANDLER': 'appointments.exceptions.custom_exception_handler',
    # ---- Rate limiting (brute-force / abuse protection) ----
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',        # unauthenticated requests per IP
        'user': '120/min',       # authenticated requests per user
        'auth': '5/min',         # login/signup attempts (scope='auth')
        'predict': '20/min',     # ML inference endpoints (scope='predict')
        'ocr': '10/min',         # OCR uploads (scope='ocr')
        'ai': '20/min',          # AI assistant questions (scope='ai') — each one
                                 # is a billable third-party LLM call, so it gets
                                 # a tighter budget than a normal read.
    },
}


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ---- Database ----
# PostgreSQL is the only supported backend. There is deliberately no SQLite
# fallback: a fallback means development, tests and production can disagree
# about transactional semantics, JSON containment, constraint deferral and
# collation — differences that surface first in production, which is the worst
# place to find them.
#
# Every value is environment-driven, so moving between development, test and
# production is configuration rather than a code change.


def _int_env(name, default):
    """An integer setting that tolerates a blank or malformed .env value."""
    try:
        return int(os.environ.get(name) or default)
    except ValueError:
        return int(default)


DB_NAME = os.environ.get('DB_NAME', 'roshada')
DB_USER = os.environ.get('DB_USER', 'postgres')
DB_PASSWORD = os.environ.get('DB_PASSWORD', '')
DB_HOST = os.environ.get('DB_HOST', 'localhost')
DB_PORT = os.environ.get('DB_PORT', '5432')

# Mirrors the SECRET_KEY rule above: a blank password is a normal local
# convenience (trust/peer auth) but never acceptable once DEBUG is off, and
# failing at startup beats failing on the first request.
if not DEBUG and not DB_PASSWORD:
    raise RuntimeError(
        'DB_PASSWORD environment variable must be set when DEBUG is False.'
    )

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        # Persistent connections: reconnecting per request is a measurable cost
        # against PostgreSQL in a way it never was against a local file.
        'CONN_MAX_AGE': _int_env('DB_CONN_MAX_AGE', 60),
        # Without this, a pooled connection killed server-side (restart,
        # failover, idle timeout) is handed to a view and fails mid-request.
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'connect_timeout': _int_env('DB_CONNECT_TIMEOUT', 10),
            # Bound any single statement so a runaway query cannot pin a
            # connection indefinitely. 0 disables it.
            'options': f"-c statement_timeout={_int_env('DB_STATEMENT_TIMEOUT_MS', 30000)}",
        },
        'TEST': {
            # Named explicitly so a test run can never be pointed at the
            # development database by an unlucky environment.
            'NAME': os.environ.get('DB_TEST_NAME', f'test_{DB_NAME}'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# ---- Uploaded media (imaging files) ----
# Patient imaging is private healthcare data, so this is deliberately NOT wired
# into the URLconf: there is no MEDIA_URL route and no static serving. The only
# way to read one of these files is the authorization-checking endpoint in
# ``radiology.views``, which verifies the caller's relationship to the study
# before streaming it. Adding ``static(settings.MEDIA_URL, ...)`` to urls.py
# would make every scan on the platform world-readable to anyone with the path.
MEDIA_ROOT = os.environ.get(
    'MEDIA_ROOT', str(BASE_DIR / 'media'))
# Kept for Django's internal use (FileField.url); never routed.
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Third-party secret, read from the environment only. Never hardcode secrets here.
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')

# ---- Logging ----
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'logs' / 'app.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'appointments': {
            'handlers': ['console', 'file'],
            'level': os.environ.get('APP_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
# Ensure the log directory exists.
(BASE_DIR / 'logs').mkdir(exist_ok=True)


# ---- Upload hardening ----
# Reject oversized request bodies / uploads before they reach a view (bytes).
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100

# ---- Security headers / cookies ----
# Applied always; the stricter HTTPS-only options activate when DEBUG is off.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Security hardening applied automatically when DEBUG is off (production).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')