# Generated by Django 5.2.16 on 2026-08-16 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="comms.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("appointment_created", "Appointment booked"),
                            ("appointment_confirmed", "Appointment confirmed"),
                            ("appointment_cancelled", "Appointment cancelled"),
                            ("appointment_rescheduled", "Appointment rescheduled"),
                            ("appointment_reminder", "Appointment reminder"),
                            ("appointment_completed", "Visit completed"),
                            ("prescription_created", "New prescription"),
                            ("prescription_updated", "Prescription updated"),
                            ("lab_result_released", "Laboratory result available"),
                            ("radiology_report_released", "Radiology report available"),
                            ("imaging_order_created", "Imaging requested"),
                            ("screening_flagged", "Screening flagged elevated risk"),
                            ("pharmacy_request_created", "New medication request"),
                            (
                                "pharmacy_request_confirmed",
                                "Medication request confirmed",
                            ),
                            (
                                "pharmacy_request_rejected",
                                "Medication request rejected",
                            ),
                            ("pharmacy_order_preparing", "Medication being prepared"),
                            ("pharmacy_order_ready", "Medication ready for pickup"),
                            ("pharmacy_order_completed", "Medication collected"),
                            (
                                "pharmacy_request_cancelled",
                                "Medication request cancelled",
                            ),
                            ("message_received", "New message"),
                            ("system_notification", "Roshada"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.CharField(blank=True, default="", max_length=300)),
                ("source", models.CharField(blank=True, default="", max_length=60)),
                ("reference", models.PositiveIntegerField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["patient", "-last_message_at"],
                name="comms_conve_patient_816448_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["doctor", "-last_message_at"],
                name="comms_conve_doctor__e54605_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("patient", "doctor"), name="one_conversation_per_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="comms_messa_convers_4ede35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "read_at"],
                name="comms_messa_convers_218a18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="comms_notif_recipie_63bc40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read_at"], name="comms_notif_recipie_acf629_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["type"], name="comms_notif_type_043298_idx"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "appointment_reminder")),
                fields=("recipient", "type", "source", "reference"),
                name="one_reminder_per_appointment",
            ),
        ),
    ]
