# Generated by Django 5.2.16 on 2026-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("appointment_created", "Appointment booked"),
                    ("appointment_confirmed", "Appointment confirmed"),
                    ("appointment_cancelled", "Appointment cancelled"),
                    ("appointment_rescheduled", "Appointment rescheduled"),
                    ("appointment_reminder", "Appointment reminder"),
                    ("appointment_completed", "Visit completed"),
                    ("prescription_created", "New prescription"),
                    ("prescription_updated", "Prescription updated"),
                    ("lab_result_released", "Laboratory result available"),
                    ("radiology_report_released", "Radiology report available"),
                    ("imaging_order_created", "Imaging requested"),
                    ("pharmacy_request_created", "New medication request"),
                    ("pharmacy_request_confirmed", "Medication request confirmed"),
                    ("pharmacy_request_rejected", "Medication request rejected"),
                    ("pharmacy_order_preparing", "Medication being prepared"),
                    ("pharmacy_order_ready", "Medication ready for pickup"),
                    ("pharmacy_order_completed", "Medication collected"),
                    ("pharmacy_request_cancelled", "Medication request cancelled"),
                    ("message_received", "New message"),
                    ("system_notification", "Roshada"),
                ],
                max_length=40,
            ),
        ),
    ]
