# Generated by Django 5.2.16 on 2026-07-13 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-date", "-time"]},
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="medical_history",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "date"], name="appointment_patient_83aa7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "date"], name="appointment_doctor__e7d63f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["available"], name="appointment_availab_a1e196_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("doctor", "date", "time"), name="unique_doctor_timeslot"
            ),
        ),
    ]
