# Generated by Django 5.2.16 on 2026-08-09 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_alter_appointment_options_alter_doctor_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screening_type",
                    models.CharField(
                        choices=[
                            ("heart", "Heart disease"),
                            ("diabetes", "Diabetes"),
                            ("brain_tumor", "Brain tumor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prediction", models.CharField(max_length=20)),
                ("is_high_risk", models.BooleanField(default=False)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "model_version",
                    models.CharField(default="unversioned", max_length=40),
                ),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_doctor_timeslot",
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("no_show", "No show"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "scheduled")),
                fields=("doctor", "date", "time"),
                name="unique_active_doctor_timeslot",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="screeningresult",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screening_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["user", "created_at"], name="appointment_user_id_bee940_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="screeningresult",
            index=models.Index(
                fields=["patient", "-created_at"], name="appointment_patient_aaee67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="screeningresult",
            index=models.Index(
                fields=["patient", "screening_type", "-created_at"],
                name="appointment_patient_6a5483_idx",
            ),
        ),
    ]
