# Generated by Django 5.2.16 on 2026-08-14 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_chatmessage_screeningresult_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("source", models.CharField(max_length=500, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("text", "Plain text"), ("markdown", "Markdown")],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(
                        fields=["source_type"], name="appointment_source__cbb95f_idx"
                    ),
                    models.Index(
                        fields=["checksum"], name="appointment_checksu_d862b9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                ("section", models.CharField(blank=True, default="", max_length=300)),
                ("embedder", models.CharField(max_length=40)),
                ("embedding_model", models.CharField(max_length=100)),
                ("dimension", models.PositiveIntegerField()),
                ("embedding", models.BinaryField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="appointments.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document_id", "ordinal"],
                "indexes": [
                    models.Index(
                        fields=["embedder", "embedding_model", "dimension"],
                        name="chunk_space_idx",
                    ),
                    models.Index(
                        fields=["document", "ordinal"],
                        name="appointment_documen_dc508c_idx",
                    ),
                    models.Index(
                        fields=["section"], name="appointment_section_49522c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "ordinal", "embedder", "embedding_model"),
                        name="unique_chunk_per_embedding_space",
                    )
                ],
            },
        ),
    ]
