# Generated by Django 5.2.16 on 2026-08-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_document_documentchunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="clinic",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="doctor",
            name="license_number",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="doctor",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
