# Generated by Django 5.2.16 on 2026-08-15 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0005_doctor_clinic_doctor_license_number_doctor_phone_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="end_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="start_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("preparation", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_minutes", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_rules",
                        to="appointments.service",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "date", "start_time"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="appointments.service",
            ),
        ),
        migrations.CreateModel(
            name="TimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "time off",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["provider", "is_active"], name="appointment_provide_8de3cf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("provider", "name"), name="unique_service_name_per_provider"
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityrule",
            index=models.Index(
                fields=["provider", "is_active"], name="appointment_provide_e221a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityrule",
            index=models.Index(
                fields=["provider", "weekday"], name="appointment_provide_ac93e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityrule",
            index=models.Index(
                fields=["provider", "date"], name="appointment_provide_85636e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="availability_ends_after_it_starts",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("date__isnull", True), ("weekday__isnull", False)),
                    models.Q(("date__isnull", False), ("weekday__isnull", True)),
                    _connector="OR",
                ),
                name="availability_is_weekly_or_dated_not_both",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot_minutes__gte", 5)),
                name="availability_slot_is_at_least_five_minutes",
            ),
        ),
        migrations.AddIndex(
            model_name="timeoff",
            index=models.Index(
                fields=["provider", "date"], name="appointment_provide_6b5fdf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeoff",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("end_time__isnull", True), ("start_time__isnull", True)),
                    models.Q(
                        ("end_time__isnull", False), ("start_time__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="time_off_window_is_complete_or_absent",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeoff",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_time__isnull", True),
                    ("end_time__gt", models.F("start_time")),
                    _connector="OR",
                ),
                name="time_off_ends_after_it_starts",
            ),
        ),
    ]
