# Generated by Django 5.2.16 on 2026-08-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_unified_appointment_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
