# Generated by Django 5.2.16 on 2026-08-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0009_service_category"),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("guideline", "Clinical guideline"),
                    ("leaflet", "Patient leaflet"),
                    ("reference", "Reference material"),
                    ("article", "Article"),
                    ("other", "Other"),
                ],
                default="reference",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="knowledge/documents/"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="document",
            name="knowledge_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="knowledge.knowledgesource",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="language",
            field=models.CharField(blank=True, default="en", max_length=20),
        ),
        migrations.AddField(
            model_name="document",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                    ("archived", "Archived"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_by",
                to="appointments.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="document",
            name="source",
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="appointment_status_4ee875_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["knowledge_source", "status"],
                name="appointment_knowled_aff47e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["source", "-version"], name="appointment_source_bdc1dd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("source", "version"), name="unique_document_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("source",),
                name="one_active_version_per_source",
            ),
        ),
    ]
