# Generated by Django 5.2.16 on 2026-08-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0010_document_description_document_document_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScreeningResult",
        ),
    ]
