# Generated by Django 5.2.16 on 2026-08-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_delete_screeningresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="pending_action",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
