# Generated by Django 5.2.16 on 2026-08-15 17:21

import django.db.models.deletion
import radiology.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0009_service_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("xray", "X-Ray"),
                            ("ct", "CT Scan"),
                            ("mri", "MRI"),
                            ("ultrasound", "Ultrasound"),
                            ("doppler", "Doppler"),
                            ("mammography", "Mammography"),
                        ],
                        max_length=20,
                    ),
                ),
                ("study_name", models.CharField(max_length=200)),
                ("clinical_indication", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In progress"),
                            ("report_pending", "Report pending"),
                            ("reported", "Reported"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordered_imaging",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imaging_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("checked_in", "Checked in"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examination",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_examinations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="examinations",
                        to="radiology.imagingorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RadiologyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("findings", models.TextField(blank=True, default="")),
                ("impression", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending review"),
                            ("verified", "Verified"),
                            ("released", "Released"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("report_date", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "examination",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="radiology.examination",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImagingFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=radiology.models.imaging_upload_path),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("document", "Document")],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "modality_code",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("study_uid", models.CharField(blank=True, default="", max_length=128)),
                (
                    "series_uid",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "instance_uid",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="radiology.examination",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_imaging",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["examination", "uploaded_at"],
                        name="radiology_i_examina_36fb4c_idx",
                    ),
                    models.Index(
                        fields=["study_uid"], name="radiology_i_study_u_db3d50_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="imagingorder",
            index=models.Index(
                fields=["patient", "-created_at"], name="radiology_i_patient_eecb65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingorder",
            index=models.Index(
                fields=["doctor", "-created_at"], name="radiology_i_doctor__fae9e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingorder",
            index=models.Index(fields=["status"], name="radiology_i_status_3ae9a7_idx"),
        ),
        migrations.AddIndex(
            model_name="imagingorder",
            index=models.Index(
                fields=["modality"], name="radiology_i_modalit_8b6425_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examination",
            index=models.Index(fields=["status"], name="radiology_e_status_555961_idx"),
        ),
        migrations.AddIndex(
            model_name="examination",
            index=models.Index(fields=["order"], name="radiology_e_order_i_d82c93_idx"),
        ),
        migrations.AddIndex(
            model_name="radiologyreport",
            index=models.Index(fields=["status"], name="radiology_r_status_72be62_idx"),
        ),
        migrations.AddIndex(
            model_name="radiologyreport",
            index=models.Index(
                fields=["-released_at"], name="radiology_r_release_350344_idx"
            ),
        ),
    ]
