"""Notifications and patient↔doctor messaging.

**One notification table for the whole platform.** There is no
``DoctorNotification``, ``LabNotification``, ``RadiologyNotification`` or
``PharmacyNotification`` — every module raises the same kind of row through
``comms.notifications.notify``. A test asserts this app owns exactly three
models and none of those names.

**Notifications carry no clinical content.** A notification says *that*
something happened and links to where it lives; the content stays in the module
that owns it, behind that module's own permission check. "Your radiology report
is available" is the whole body — never the impression, never the result,
never the text of a message.
"""
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from django.utils import timezone

from . import types


class Notification(models.Model):
    """One thing that happened, addressed to one user.

    ``source``/``reference`` are the same reference shape the medical record
    uses: the app-and-model label plus an id, enough for the client to open the
    record through the module that owns it, and not enough to read it without
    that module's permission check.

    Read state is a nullable timestamp rather than a boolean: it answers both
    "is it read" and "when", and marking everything read is a single UPDATE.
    """

    recipient = models.ForeignKey(User, on_delete=models.CASCADE,
                                  related_name="notifications")
    type = models.CharField(max_length=40, choices=types.CHOICES)
    title = models.CharField(max_length=160)
    #: One short sentence. Deliberately not a place to put clinical detail —
    #: see the module docstring.
    body = models.CharField(max_length=300, blank=True, default="")
    #: "app_label.ModelName" of the record this is about, when there is one.
    source = models.CharField(max_length=60, blank=True, default="")
    reference = models.PositiveIntegerField(null=True, blank=True)
    read_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["recipient", "-created_at"]),
            # The unread badge reads this one: recipient + null read_at.
            models.Index(fields=["recipient", "read_at"]),
            models.Index(fields=["type"]),
        ]
        constraints = [
            # A reminder is generated by a command that may be run more than
            # once; without this, a second run would notify the patient again
            # about the same appointment. Partial, because every other kind can
            # legitimately repeat — two messages in one conversation are two
            # events, not a duplicate.
            models.UniqueConstraint(
                fields=["recipient", "type", "source", "reference"],
                condition=Q(type=types.APPOINTMENT_REMINDER),
                name="one_reminder_per_appointment"),
        ]

    def __str__(self):
        return f"{self.type} -> {self.recipient.username}"

    @property
    def is_read(self):
        return self.read_at is not None

    @property
    def category(self):
        return types.category_of(self.type)

    @property
    def type_label(self):
        return types.label(self.type)

    def mark_read(self):
        if self.read_at is None:
            self.read_at = timezone.now()
            self.save(update_fields=["read_at"])
        return self

    def mark_unread(self):
        if self.read_at is not None:
            self.read_at = None
            self.save(update_fields=["read_at"])
        return self


class Conversation(models.Model):
    """A thread between one patient and one doctor.

    Not a general chat: a conversation may only exist where the platform's
    existing care relationship does, and the pair is unique so the same two
    people cannot end up with two threads that each hold half the history.

    Deliberately no ``participants`` many-to-many. Roshada's messaging is
    patient↔doctor by design; a generic participant table would invite group
    threads, and a public or many-party chat is exactly what the design rules
    out.
    """

    patient = models.ForeignKey(User, on_delete=models.CASCADE,
                                related_name="patient_conversations")
    doctor = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="doctor_conversations")
    subject = models.CharField(max_length=160, blank=True, default="")
    is_active = models.BooleanField(default=True)
    #: Bumped whenever a message is added, so the conversation list can be
    #: ordered by recency without touching the message table.
    last_message_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-last_message_at", "-created_at"]
        constraints = [
            models.UniqueConstraint(fields=["patient", "doctor"],
                                    name="one_conversation_per_pair"),
        ]
        indexes = [
            models.Index(fields=["patient", "-last_message_at"]),
            models.Index(fields=["doctor", "-last_message_at"]),
        ]

    def __str__(self):
        return f"{self.patient.username} ↔ {self.doctor.username}"

    def includes(self, user):
        """Membership, asked of the row rather than re-derived by callers."""
        return user is not None and user.pk in (self.patient_id, self.doctor_id)

    def counterparty(self, user):
        """The other person in the thread, from ``user``'s point of view."""
        if user is None:
            return None
        return self.doctor if user.pk == self.patient_id else self.patient


class Message(models.Model):
    """One message in a conversation.

    Two states only — sent, and read — because that is what the product can
    honestly report. Delivery receipts would need transport the platform does
    not have, and inventing one would be a claim about whether a person
    actually got a medical message.

    No attachment field: Roshada's only file storage belongs to radiology and
    is scoped to an examination. There is no reason for a second one, so
    messaging is text for now.
    """

    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE,
                                     related_name="messages")
    sender = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="sent_messages")
    body = models.TextField()
    read_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]
        indexes = [
            models.Index(fields=["conversation", "created_at"]),
            models.Index(fields=["conversation", "read_at"]),
        ]

    def __str__(self):
        return f"message {self.pk} from {self.sender.username}"

    @property
    def is_read(self):
        return self.read_at is not None
